"""Format LLM review text + PlanSummary into a GitHub PR comment."""
from __future__ import annotations

from reviewer.parser import PlanSummary

_VERDICT_EMOJI = {
    "PASS": "✅",
    "WARN": "⚠️",
    "BLOCK": "🚫",
}


def format_comment(llm_text: str, summary: PlanSummary) -> str:
    verdict = _extract_verdict(llm_text)
    emoji = _VERDICT_EMOJI.get(verdict, "🤖")
    change_table = _change_table(summary)

    return f"""\
## 🤖 Terraform Plan AI Review

**Verdict: {emoji} {verdict}**

{change_table}

---

{llm_text.strip()}

---
<sub>Generated by [tf-plan-ai-reviewer](https://github.com/JamesIOmete/tf-plan-ai-reviewer) · Terraform {summary.terraform_version}</sub>"""


def _extract_verdict(text: str) -> str:
    upper = text.upper()
    for verdict in ("BLOCK", "WARN", "PASS"):
        if verdict in upper:
            return verdict
    return "UNKNOWN"


def _change_table(s: PlanSummary) -> str:
    rows = [
        f"| ➕ Create  | {s.add_count} |",
        f"| 🔄 Update  | {s.change_count} |",
        f"| 💥 Destroy | {s.destroy_count} |",
        f"| ♻️ Replace  | {s.replace_count} |",
    ]
    return "| Action | Count |\n|--------|-------|\n" + "\n".join(rows)
